### ISSUE TITLE
win32drv Possibility to change the window title for each display

### ISSUE THREAD

**Issue by wrgallo** [lvgl/lv_drivers#256] opened 2022-11-30 16:46 UTC
Currently by creating a display window with `lv_win32_init` the created window will have the title `L"LVGL Simulator for Windows Desktop"`, that string cannot be easily changed by user.

I am already working on a pull request to fix this issue.

**Comment by kisvegabor** [comment] 2022-12-01 09:30
@MouriNaruto could you take look at it?

**Comment by kisvegabor** [comment] 2022-12-03 16:31
Thank you!

**Comment by MouriNaruto** [comment] 2022-12-15 13:31
@kisvegabor 

The issue is also solved by https://github.com/lvgl/lv_drivers/pull/259.

Kenji Mouri

**Comment by kisvegabor** [comment] 2022-12-15 13:32
Great, I close it then.

**Closed by kisvegabor** 2022-12-15 13:32 UTC
